---
title: "ggplot.qmd"
format: html
editor: visual
theme: sketchy
toc: true
lang: es
---

```{r}
#| label: carga de paquetes 
#| menssage: false 
#| warning: false

library(tidyverse)
library(DT)
library(gapminder)
library(ggthemes)
```

```{r}
# Tabla de datos de mpg
mpg |>
  select(manufacturer, year, cty, hwy)|>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

```{r}
#| label: Diamantes
diamonds |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## Gapminder

```{r}
gapminder |>
  filter(year == 2007) |> # filtro para el año 2007
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## ggplot2

```{r}
#| label: ggplot2-01

ggplot(data = mpg) + geom_point(aes(x = displ, y = hwy))+
  theme_solarized_2()

```

```{r}
#| label: ggplot2-02

mpg|>
  ggplot(aes(x = displ, y = hwy)) +
  geom_point()+
  theme_solarized_2()

```

```{r}
#| label: ggplot2-03

mpg|>
  ggplot(aes(x = displ, y = hwy, color = class)) +
  geom_point()+
  theme_solarized_2()

```

```{r}
#| label: ggplot2-04

mpg|>
  ggplot(aes(x = displ, y = hwy, shape = class, color = class)) +
  geom_point()+
  theme_solarized_2()
```

```{r}
#| label: ggplot2-05
mpg |>
  ggplot(aes(x = displ, y = hwy, shape = class, color = class)) +
  geom_point() +
  scale_shape_manual(values = c(0, 1, 2, 3, 4, 5, 6)) +
  scale_color_manual(values = c("red", "blue", "green", "purple", "orange", "brown", "pink"))+
  theme_solarized_2()
```

```{r}
#| label: ggplot2-06

gapminder |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) + 
  geom_point()+
  theme_solarized_2()
  

```

```{r}
#| label: ggplot2-07

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) + 
  geom_point()+
  theme_solarized_2()
```

```{r}
#| label: ggplot2-08

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp, color = continent)) + 
  geom_point() + geom_smooth(method = "lm")+
  theme_solarized_2()

```

```{r}
#| label: ggplot2-09
#|

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) + 
  geom_point() + geom_smooth(method = "lm") +
  ggtitle("Relaciónes entre el PIB per capita y esperanza de vida 2007") +
  xlab("PIB per capita EEUU ($)") +
  ylab("Esperanza de vida en (años)") +
  theme_solarized_2()

```
